apiVersion: v2
name: library
description: An example Helm chart for the library application
type: application
version: 0.0.1
appVersion: 1.0.0

dependencies:
  - name: ingress-nginx
    version: 4.2.5
    repository: https://kubernetes.github.io/ingress-nginx
    condition: nginx.enabled