apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library.fullname" . }}-secrets
  labels:
    {{- include "library.labels" . | nindent 4 }}
data:
  APP_SECURITY_USERNAME: "YWRtaW4=" # admin
  APP_SECURITY_PASSWORD: "c2VjcmV0" # secret