apiVersion: v1
kind: Pod
metadata:
  name: pg-client
  namespace: infra
  labels:
    app: pg-client
spec:
  containers:
    - name: postgresql
      image: bitnami/postgresql:11.12.0-debian-10-r13
      imagePullPolicy: IfNotPresent
      env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
  restartPolicy: Always
