apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  template:
    metadata:
      name: kuard
      labels:
        app: kuard
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: kuard
