apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-amd64:2
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          name: http
      startupProbe:
        httpGet:
          port: http
          path: /healthy
        timeoutSeconds: 1
        periodSeconds: 5
        failureThreshold: 6
      livenessProbe:
        httpGet:
          port: http
          path: /healthy
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          port: http
          path: /ready
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
