apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc
  namespace: infra
spec:
  selector:
    app: pgpool
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
      nodePort: null
  type: ClusterIP
  sessionAffinity: None