apiVersion: v1
kind: LimitRange
metadata:
  namespace: library
  name: library-limit-range
spec:
  limits:
    - type: Container
      min:
        cpu: "100m"
      max:
        cpu: "1000m"
        memory: "2Gi"
  