apiVersion: v1
kind: ResourceQuota
metadata:
  name: library-resource-quota-memory-cpu
  namespace: library
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "16Gi"
    limits.cpu: "6"
    limits.memory: "24Gi"
