apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
  namespace: library
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://pgpool-svc.infra/postgres
  SPRING_PROFILES_ACTIVE: "admin"
  SPRING_CLOUD_VAULT_ENABLED: "true"
  SPRING_CLOUD_VAULT_HOST: vault
  SPRING_CLOUD_VAULT_PORT: "8200"
  SPRING_CLOUD_VAULT_SCHEME: http
  SPRING_CLOUD_VAULT_URI: http://vault-dev.infra:8200
  SPRING_CLOUD_VAULT_AUTHENTICATION: kubernetes
  SPRING_CLOUD_VAULT_KUBERNETES_ROLE: library
#  SPRING_CLOUD_VAULT_AUTHENTICATION: token
#  SPRING_CLOUD_VAULT_TOKEN: hvs.bnLwmg5nbbsFm32jrjns7fit
  SPRING_CLOUD_VAULT_KV_ENABLED: "false"
  SPRING_CLOUD_VAULT_CONFIG_LIFECYCLE_ENABLED: "true"
  SPRING_CLOUD_VAULT_CONFIG_LIFECYCLE_MIN_RENEWAL: 4m
  SPRING_CLOUD_VAULT_CONFIG_LIFECYCLE_EXPIRY_THRESHOLD: 5m
  SPRING_CLOUD_VAULT_DATABASE_ENABLED: "true"
  SPRING_CLOUD_VAULT_DATABASE_ROLE: library
  SPRING_CLOUD_VAULT_DATABASE_BACKEND: database